site_name: Documentation BlueRockTEL en Français
site_url: https://bluerocktel.github.io/documentation-fr/
site_description: Documentation de BlueRockLTEL en langue française
site_author: Cyrille Georgel < cyrille.georgel@bluerocktel.net >
nav:
  - Home: index.md
  - Préparer vos données pour l'intégration dans BlueRockTEL :
      - 'Le pack BlueRockTEL': bluerocktel_pack.md
      - 'Clients': bluerocktel_pack_clients.md
theme:
  name: readthedocs
  custom_dir: override
  plugins:
    - search
    - mkpdfs
